"""Apply slot capacity fields and fix appointment relationship

Revision ID: 5166eadd800b
Revises: 20973ecf4843
Create Date: 2025-10-25 23:40:25.914638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5166eadd800b'
down_revision: Union[str, Sequence[str], None] = '20973ecf4843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment_slots', sa.Column('max_strict_capacity', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('appointment_slots', sa.Column('current_strict_appointments', sa.Integer(), nullable=False, server_default='0'))
    op.drop_constraint(op.f('appointment_slots_appointment_id_key'), 'appointment_slots', type_='unique')
    op.drop_index(op.f('idx_slot_appointment'), table_name='appointment_slots')
    op.drop_constraint(op.f('appointment_slots_appointment_id_fkey'), 'appointment_slots', type_='foreignkey')
    op.drop_column('appointment_slots', 'appointment_id')
    op.add_column('appointments', sa.Column('slot_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('booking_type', sa.Enum('strict', 'walk_in', name='booking_type'), nullable=False, server_default='strict'))
    op.create_index(op.f('ix_appointments_slot_id'), 'appointments', ['slot_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'appointment_slots', ['slot_id'], ['id'])

    # Manual Fix: Remove temporary server_default from new non-nullable columns
    op.alter_column('appointment_slots', 'max_strict_capacity', server_default=None, existing_type=sa.Integer(), nullable=False)
    op.alter_column('appointment_slots', 'current_strict_appointments', server_default=None, existing_type=sa.Integer(), nullable=False)
    op.alter_column('appointments', 'booking_type', server_default=None, existing_type=sa.Enum('strict', 'walk_in', name='booking_type'), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_slot_id'), table_name='appointments')
    op.drop_column('appointments', 'booking_type')
    op.drop_column('appointments', 'slot_id')
    op.add_column('appointment_slots', sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointment_slots_appointment_id_fkey'), 'appointment_slots', 'appointments', ['appointment_id'], ['id'])
    op.create_index(op.f('idx_slot_appointment'), 'appointment_slots', ['appointment_id'], unique=False)
    op.create_unique_constraint(op.f('appointment_slots_appointment_id_key'), 'appointment_slots', ['appointment_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('appointment_slots', 'current_strict_appointments')
    op.drop_column('appointment_slots', 'max_strict_capacity')
    # ### end Alembic commands ###
