"""Add emergency_block to SlotStatus enum

Revision ID: 839c539607c7
Revises: 0e4d267732b1
Create Date: 2025-10-25 21:46:54.892342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '839c539607c7'
down_revision: Union[str, Sequence[str], None] = '0e4d267732b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE slot_status ADD VALUE 'emergency_block'")
    op.drop_column('patient_menstrual_history', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downggrad schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrading an enum is complex and destructive. We will not attempt to remove
    # 'emergency_block' automatically. We will only revert the other change.
    op.add_column('patient_menstrual_history', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
